title: Neon Bites: DC's Rad Food Guide
email: neonbites@example.com
description: >-
  Discover the vibrant, gluten-free and vegetarian-friendly dining scene of Washington, DC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-polyglot

# Polyglot settings
languages: ["en", "es", "ar"]
default_lang: en
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true